# Generated by Django 5.0.7 on 2024-08-02 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('read', 'Read'), ('update', 'Update')], max_length=10)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_permissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='taskpermission',
            constraint=models.UniqueConstraint(fields=('task', 'user', 'permission_type'), name='unique_task_permission'),
        ),
        migrations.AlterUniqueTogether(
            name='taskpermission',
            unique_together={('task', 'user', 'permission_type')},
        ),
    ]
